# Generated by Django 6.0.3 on 2026-04-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="linkedin",
            field=models.URLField(blank=True),
        ),
    ]
