# Generated by Django 6.0.3 on 2026-04-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0002_alter_docente_linkedin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("resumo_basico", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_comeco", models.DateField()),
                ("data_saida", models.DateField()),
                ("competencias", models.ManyToManyField(to="portifolio.competencias")),
            ],
        ),
    ]
