# Generated by Django 6.0.3 on 2026-04-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0003_competencias_empresa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formacoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("data", models.DateField()),
                ("resumo", models.CharField(max_length=200)),
            ],
        ),
    ]
