# Generated by Django 6.0.3 on 2026-04-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0004_formacoes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Competencias",
            new_name="Competencia",
        ),
        migrations.RenameModel(
            old_name="Formacoes",
            new_name="Formacao",
        ),
    ]
