# Generated by Django 6.0.3 on 2026-04-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0005_rename_competencias_competencia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("autor", models.CharField(max_length=100)),
                ("tecnologias_usadas", models.CharField(max_length=100)),
                ("resumo", models.CharField(max_length=500)),
                ("video_imagem", models.URLField()),
                ("interesse", models.DecimalField(decimal_places=1, max_digits=2)),
                (
                    "docente_responsavel",
                    models.ManyToManyField(to="portifolio.docente"),
                ),
            ],
        ),
    ]
