# Generated by Django 6.0.3 on 2026-04-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0006_tfc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
    ]
