# Generated by Django 6.0.3 on 2026-04-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0007_tecnologia"),
    ]

    operations = [
        migrations.AddField(
            model_name="tecnologia",
            name="descricao",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="docente",
            field=models.ManyToManyField(to="portifolio.docente"),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="exemplos_uso",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="logo",
            field=models.ImageField(null=True, upload_to="logos/"),
        ),
    ]
