# Generated by Django 6.0.3 on 2026-04-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0008_tecnologia_descricao_tecnologia_docente_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("nota_final", models.DecimalField(decimal_places=1, max_digits=2)),
                ("descricao", models.CharField(max_length=200)),
                ("exemplo", models.ImageField(null=True, upload_to="projetos/")),
                ("link_deisi", models.URLField(null=True)),
                ("docentes", models.ManyToManyField(to="portifolio.docente")),
                (
                    "tecnologias_usadas",
                    models.ManyToManyField(to="portifolio.tecnologia"),
                ),
            ],
        ),
    ]
