# Generated by Django 6.0.3 on 2026-04-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0009_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="UC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("resumo", models.CharField(max_length=100)),
                ("docentes", models.ManyToManyField(to="portifolio.docente")),
                (
                    "projeto_final",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portifolio.projeto",
                    ),
                ),
                (
                    "tecnologias_aprendidas",
                    models.ManyToManyField(to="portifolio.tecnologia"),
                ),
            ],
        ),
    ]
