# Generated by Django 6.0.3 on 2026-04-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0010_uc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("objetivos", models.CharField(max_length=500)),
                ("docentes", models.ManyToManyField(to="portifolio.docente")),
                ("tecnologias", models.ManyToManyField(to="portifolio.tecnologia")),
                ("ucs", models.ManyToManyField(to="portifolio.uc")),
            ],
        ),
    ]
