# Generated by Django 6.0.3 on 2026-04-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0011_licenciatura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="data_saida",
            field=models.DateField(null=True),
        ),
    ]
