# Generated by Django 6.0.3 on 2026-04-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0012_alter_empresa_data_saida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="data_saida",
            field=models.DateField(blank=True, null=True),
        ),
    ]
