# Generated by Django 6.0.3 on 2026-04-05 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0013_alter_empresa_data_saida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competencia",
            name="resumo_basico",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="resumo",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="objetivos",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="exemplo",
            field=models.ImageField(blank=True, null=True, upload_to="projetos/"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="link_deisi",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="video_imagem",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="uc",
            name="projeto_final",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portifolio.projeto",
            ),
        ),
    ]
