# Generated by Django 6.0.3 on 2026-04-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0014_alter_competencia_resumo_basico_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="nota_final",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
