# Generated by Django 6.0.3 on 2026-04-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0015_alter_projeto_nota_final"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakingOF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("resumo", models.CharField(blank=True, max_length=100)),
                ("arquivo", models.FileField(blank=True, upload_to="documentos/")),
            ],
        ),
    ]
