# Generated by Django 6.0.3 on 2026-04-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0016_makingof"),
    ]

    operations = [
        migrations.AddField(
            model_name="makingof",
            name="imagem",
            field=models.ImageField(blank=True, upload_to="makingOF/"),
        ),
    ]
