# Generated by Django 6.0.3 on 2026-04-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0017_makingof_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
    ]
