# Generated by Django 6.0.3 on 2026-04-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0018_alter_docente_linkedin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="docente",
            old_name="linkedin",
            new_name="link",
        ),
    ]
