# Generated by Django 6.0.3 on 2026-04-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0019_rename_linkedin_docente_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="competencias",
            field=models.ManyToManyField(
                blank=True, null=True, to="portifolio.competencia"
            ),
        ),
    ]
