# Generated by Django 6.0.3 on 2026-04-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0020_alter_empresa_competencias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenciatura",
            name="ucs",
            field=models.ManyToManyField(blank=True, to="portifolio.uc"),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="docente",
            field=models.ManyToManyField(blank=True, to="portifolio.docente"),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="resumo",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
