# Generated by Django 6.0.3 on 2026-04-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0021_alter_licenciatura_ucs_alter_tecnologia_docente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="tecnologias_usadas",
            field=models.ManyToManyField(blank=True, to="portifolio.tecnologia"),
        ),
    ]
