# Generated by Django 6.0.3 on 2026-04-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0022_alter_projeto_tecnologias_usadas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="tecnologias_usadas",
            field=models.ManyToManyField(to="portifolio.tecnologia"),
        ),
    ]
