# Generated by Django 6.0.3 on 2026-04-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0024_alter_empresa_competencias"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tfc",
            name="docente_responsavel",
        ),
        migrations.AddField(
            model_name="tfc",
            name="docente_responsavel",
            field=models.CharField(blank=True),
        ),
    ]
