# Generated by Django 6.0.3 on 2026-04-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0025_remove_tfc_docente_responsavel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="docente",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
