# Generated by Django 6.0.3 on 2026-04-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0026_docente_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="licenciatura",
            name="tecnologias",
        ),
        migrations.AlterField(
            model_name="uc",
            name="tecnologias_aprendidas",
            field=models.ManyToManyField(blank=True, to="portifolio.tecnologia"),
        ),
    ]
