# Generated by Django 6.0.3 on 2026-04-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0027_remove_licenciatura_tecnologias_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uc",
            name="ano_curricular",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uc",
            name="ect",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uc",
            name="semestre",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
