# Generated by Django 6.0.3 on 2026-04-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0028_uc_ano_curricular_uc_ect_uc_semestre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uc",
            name="ano_curricular",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="uc",
            name="ect",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="uc",
            name="semestre",
            field=models.IntegerField(null=True),
        ),
    ]
