# Generated by Django 6.0.3 on 2026-04-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0029_alter_uc_ano_curricular_alter_uc_ect_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uc",
            name="nome",
            field=models.CharField(max_length=500),
        ),
    ]
