# Generated by Django 6.0.3 on 2026-04-08 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0030_alter_uc_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenciatura",
            name="diretor_curso",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diretor_de_curso",
                to="portifolio.docente",
            ),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="docentes",
            field=models.ManyToManyField(
                blank=True, related_name="licenciaturas", to="portifolio.docente"
            ),
        ),
    ]
