# Generated by Django 6.0.3 on 2026-04-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0031_licenciatura_diretor_curso_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competencia",
            options={"ordering": ["titulo"]},
        ),
        migrations.AlterModelOptions(
            name="docente",
            options={"ordering": ["nome"]},
        ),
        migrations.AlterModelOptions(
            name="formacao",
            options={"ordering": ["titulo"]},
        ),
        migrations.AlterModelOptions(
            name="licenciatura",
            options={"ordering": ["nome"]},
        ),
        migrations.AlterModelOptions(
            name="projeto",
            options={"ordering": ["titulo"]},
        ),
        migrations.AlterModelOptions(
            name="tecnologia",
            options={"ordering": ["nome"]},
        ),
        migrations.AlterModelOptions(
            name="tfc",
            options={"ordering": ["titulo"]},
        ),
        migrations.AlterModelOptions(
            name="uc",
            options={"ordering": ["nome"]},
        ),
    ]
