# Generated by Django 6.0.3 on 2026-05-02 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("resumo_basico", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["titulo"],
            },
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("link", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("data", models.DateField()),
                ("resumo", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["titulo"],
            },
        ),
        migrations.CreateModel(
            name="MakingOF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("resumo", models.CharField(blank=True, max_length=100)),
                ("arquivo", models.FileField(blank=True, upload_to="documentos/")),
                ("imagem", models.ImageField(blank=True, upload_to="makingOF/")),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("autor", models.CharField(max_length=100)),
                ("docente_responsavel", models.CharField(blank=True)),
                ("tecnologias_usadas", models.CharField(max_length=100)),
                ("resumo", models.CharField(blank=True, max_length=500)),
                ("video_imagem", models.URLField(blank=True)),
                ("interesse", models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                "ordering": ["titulo"],
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_comeco", models.DateField()),
                ("data_saida", models.DateField(blank=True, null=True)),
                (
                    "competencias",
                    models.ManyToManyField(blank=True, to="portfolio.competencia"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=200, null=True)),
                ("exemplos_uso", models.CharField(max_length=200, null=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("docente", models.ManyToManyField(blank=True, to="portfolio.docente")),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("nota_final", models.DecimalField(decimal_places=1, max_digits=3)),
                ("descricao", models.CharField(max_length=200)),
                (
                    "exemplo",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("link_deisi", models.URLField(blank=True, null=True)),
                ("docentes", models.ManyToManyField(to="portfolio.docente")),
                (
                    "tecnologias_usadas",
                    models.ManyToManyField(to="portfolio.tecnologia"),
                ),
            ],
            options={
                "ordering": ["titulo"],
            },
        ),
        migrations.CreateModel(
            name="UC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=500)),
                ("resumo", models.CharField(max_length=100)),
                ("ect", models.IntegerField(null=True)),
                ("ano_curricular", models.IntegerField(null=True)),
                ("semestre", models.IntegerField(null=True)),
                ("docentes", models.ManyToManyField(to="portfolio.docente")),
                (
                    "projeto_final",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portfolio.projeto",
                    ),
                ),
                (
                    "tecnologias_aprendidas",
                    models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("objetivos", models.CharField(blank=True, max_length=500)),
                (
                    "diretor_curso",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diretor_de_curso",
                        to="portfolio.docente",
                    ),
                ),
                (
                    "docentes",
                    models.ManyToManyField(
                        blank=True, related_name="licenciaturas", to="portfolio.docente"
                    ),
                ),
                ("ucs", models.ManyToManyField(blank=True, to="portfolio.uc")),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
    ]
