# Generated by Django 6.0.5 on 2026-05-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="resumo",
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
