# Generated by Django 6.0.5 on 2026-05-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_tfc_resumo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(max_length=500),
        ),
    ]
