# Generated by Django 6.0.5 on 2026-05-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_tfc_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="tecnologias_usadas",
            field=models.CharField(max_length=500),
        ),
    ]
