# Generated by Django 6.0.5 on 2026-05-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_alter_tfc_tecnologias_usadas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="autor",
            field=models.CharField(max_length=200),
        ),
    ]
