from django.urls import path, include
from . import views

urlpatterns = [
   path("", views.ucs_view, name='ucs'),
   path("ucs/", views.ucs_view, name='ucs'),
   path("ucs/<int:id>/", views.uc_view, name='uc'),
   path("projetos/", views.projetos_view, name='projetos'),
   path("projetos/<int:id>/", views.projeto_view, name='projeto'),
   path("licenciaturas/", views.licenciaturas_view, name='licenciaturas'),
   path("licenciaturas/<int:id>/", views.licenciatura_view, name='licenciatura'),
   path("docentes/<int:id>/", views.docente_view, name='docente'),
   path("empresas/", views.empresas_view, name='empresas'),
   path("tfcs/", views.tfcs_view, name='tfcs'),
   path('projetos/novo', views.novo_projeto_view, name="novo_projeto"),
   path('projeto/<int:projeto_id>/edita', views.edita_projeto_view,name="edita_projeto"),
   path('projeto/<int:projeto_id>/apaga', views.apaga_projeto_view,name="apaga_projeto"),
   path("tecnologias/", views.tecnologias_view, name='tecnologias'),
   path("tecnologia/<int:id>/", views.tecnologia_view, name='tecnologia'),
   path('tecnologias/novo', views.nova_tecnologia_view, name="nova_tecnologia"),
   path('tecnologia/<int:tecnologia_id>/edita', views.edita_tecnologia_view,name="edita_tecnologia"),
   path('tecnologia/<int:tecnologia_id>/apaga', views.apaga_tecnologia_view,name="apaga_tecnologia"),
   path("competencias/", views.competencias_view, name='competencias'),
   path("competencia/<int:id>/", views.competencia_view, name='competencia'),
   path('competencia/<int:competencia_id>/edita', views.edita_competencia_view,name="edita_competencia"),
   path('competencia/<int:competencia_id>/apaga', views.apaga_competencia_view,name="apaga_competencia"),
   path('competencia/nova', views.nova_competencia_view, name="nova_competencia"),
   path("formacoes/", views.formacoes_view, name='formacoes'),
   path("formacao/<int:id>/", views.formacao_view, name='formacao'),
   path('formacao/nova', views.nova_formacao_view, name="nova_formacao"),
   path('formacao/<int:formacao_id>/edita', views.edita_formacao_view,name="edita_formacao"),
   path('formacao/<int:formacao_id>/apaga', views.apaga_formacao_view,name="apaga_formacao"),
   path("info/", views.info_view, name='info'),
   path("login/", views.login_view, name='login'),
   path("registo/", views.registo_view, name='registo'),
   path("conta/", views.account_view, name='conta'),
   path("logout/", views.logout_view, name='logout'),

]
